# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
