# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20170420_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='wating',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
