# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_source_wating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='wating',
            new_name='waiting',
        ),
    ]
