# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20170421_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='img',
            field=models.ImageField(max_length=255, null=True, upload_to='sources'),
        ),
    ]
