# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_source_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='landmark',
            field=models.CharField(default='', max_length=200, verbose_name='Ориентир'),
        ),
        migrations.AddField(
            model_name='source',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='source',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='source',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='source',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='pressure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='waiting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
