# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20170510_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(default='', verbose_name='Описание (html)'),
        ),
        migrations.AddField(
            model_name='source',
            name='route',
            field=models.TextField(default='', verbose_name='Как проехать (html)'),
        ),
    ]
