# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20170510_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание (html)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='distance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ориентир'),
        ),
        migrations.AlterField(
            model_name='source',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='source',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='source',
            name='pressure',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='rating',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='route',
            field=models.TextField(blank=True, default='', verbose_name='Как проехать (html)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='visitors',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='waiting',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
