export const SERVER_URL = `${API_URL}`

export const RECEIVED_SOURCE      = 'RECEIVED_SOURCE'

export const FETCH_SOURCE_SUCCESS = 'FETCH_SOURCE_SUCCESS'
export const FETCH_SOURCE_FAIL    = 'FETCH_SOURCE_FAIL'
export const FETCH_SOURCE_CANCEL  = 'FETCH_SOURCE_CANCEL'
